# Generated by Django 4.1.7 on 2023-03-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='follow',
            name='pending',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
