# Generated by Django 4.0.3 on 2023-03-11 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engagement', '0004_remove_follow_accepted_remove_follow_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to=settings.AUTH_USER_MODEL)),
                ('liked_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('liked_to', 'liked_by')},
            },
        ),
    ]
