# Generated by Django 4.0.3 on 2023-03-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_followers_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='engagement',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
