# Generated by Django 4.0.3 on 2023-03-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_engagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
