# Generated by Django 4.0.3 on 2023-03-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
