<<<<<<< HEAD
# Generated by Django 4.0.3 on 2023-03-11 20:34
=======
# Generated by Django 4.1.7 on 2023-03-11 20:39
>>>>>>> 72943a90a92bbb712a1c0782b6b3015b7c8a7ac5

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('desc', models.TextField(blank=True, max_length=300)),
                ('rentpday', models.IntegerField(blank=True, null=True)),
                ('image', models.URLField(blank=True)),
                ('from_date', models.CharField(max_length=10)),
                ('to_date', models.CharField(max_length=10)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
